export default function TermsAndConditions() {
  return (
    <div className="max-w-3xl mx-auto py-12 space-y-8 text-gray-300">
      <div>
        <h1 className="text-3xl font-bold text-white mb-2">Terms &amp; Conditions</h1>
        <p className="text-sm text-gray-500">Last updated: May 2025</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">1. Acceptance of Terms</h2>
        <p>
          By using Promohit you agree to these Terms &amp; Conditions. If you do not agree,
          please do not use the platform.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">2. Description of Service</h2>
        <p>
          Promohit is a platform that automates the creation and launch of Meta
          (Facebook/Instagram) advertising campaigns for music artists. We process your audio,
          generate video creatives, write ad copy using AI, and launch campaigns via the Meta
          Marketing API on your behalf.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">3. Eligibility</h2>
        <p>
          You must be at least 18 years old and have a valid Meta ad account to use Promohit.
          You are responsible for ensuring your use complies with Meta's advertising policies
          and all applicable laws.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">4. Your Content</h2>
        <p>
          You retain ownership of all audio, images, and other content you upload. By uploading
          content you grant Promohit a limited licence to process and use that content solely to
          deliver the service (generating video creatives and launching your ad campaigns). You
          confirm that you own or have the rights to any content you upload.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">5. Meta Advertising</h2>
        <p>
          Promohit creates ad campaigns on your Meta ad account using credentials you provide.
          You are solely responsible for:
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>All ad spend charged to your Meta ad account.</li>
          <li>Ensuring your campaigns comply with Meta's advertising policies.</li>
          <li>The accuracy of any claims made in your ads.</li>
          <li>Obtaining any necessary rights or licences for content used in ads.</li>
        </ul>
        <p>
          Promohit is not responsible for campaign performance, ad rejections, or charges
          applied by Meta.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">6. AI-Generated Content</h2>
        <p>
          Ad copy is generated by Claude AI (Anthropic). You should review all generated copy
          before launching a campaign. Promohit makes no guarantees about the accuracy,
          suitability, or performance of AI-generated content.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">7. Acceptable Use</h2>
        <p>You agree not to use Promohit to:</p>
        <ul className="list-disc list-inside space-y-2">
          <li>Upload content you do not own or have rights to.</li>
          <li>Create ads that violate Meta's Community Standards or advertising policies.</li>
          <li>Engage in any fraudulent, deceptive, or illegal activity.</li>
          <li>Attempt to reverse-engineer, scrape, or disrupt the platform.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">8. Limitation of Liability</h2>
        <p>
          Promohit is provided "as is" without warranties of any kind. To the fullest extent
          permitted by law, we are not liable for any indirect, incidental, or consequential
          damages arising from your use of the platform, including ad spend, lost revenue, or
          campaign underperformance.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">9. Termination</h2>
        <p>
          We reserve the right to suspend or terminate your account if you violate these Terms.
          You may stop using Promohit at any time. On termination, we will delete your data in
          accordance with our Privacy Policy.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">10. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Continued use of Promohit after changes
          are posted constitutes acceptance of the updated Terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-xl font-semibold text-white">11. Contact</h2>
        <p>
          For questions about these Terms, email{' '}
          <a href="mailto:legal@promohit.app" className="text-blue-400 hover:underline">
            legal@promohit.app
          </a>.
        </p>
      </section>
    </div>
  );
}
